task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

num_classes: 3 # your dataset classes
remap_mscoco_category: False

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /home/kyle/github/catchlog_data/detection_2025/coco/train 
    ann_file: /home/kyle/github/catchlog_data/detection_2025/coco/train/_annotations.coco.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 6
  drop_last: True
  collate_fn:
    type: BatchImageCollateFunction


val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /home/kyle/github/catchlog_data/detection_2025/coco/valid
    ann_file: /home/kyle/github/catchlog_data/detection_2025/coco/valid/_annotations.coco.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: False
  num_workers: 6
  drop_last: False
  collate_fn:
    type: BatchImageCollateFunction
